### Step 1: Import necessary libraries

In [3]:
import pandas as pd
import numpy as np

### Step 2: Load the Data

In [4]:
df = pd.read_csv('cafe_sales.csv')

### Step 3: Explore the Data

##### display the first 10 rows to see the "messy" data

In [5]:
df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

##### check how many rows and columns

In [6]:
df.shape

(10000, 8)

##### display basic info about the dataset to identify nulls and incorrect data types

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

##### check unique values for `Item`, `Payment Method`, and `Location`

In [9]:
unique_Item=  df['Item'].unique()
print(unique_Item)

['Coffee' 'Cake' 'Cookie' 'Salad' 'Smoothie' 'UNKNOWN' 'Sandwich' nan
 'ERROR' 'Juice' 'Tea']

In [10]:
unique_location=  df['Location'].unique()
print(unique_location)

['Takeaway' 'In-store' 'UNKNOWN' nan 'ERROR']

In [11]:
unique_pay=  df['Payment Method'].unique()
print(unique_pay)

['Credit Card' 'Cash' 'UNKNOWN' 'Digital Wallet' 'ERROR' nan]

##### check missing values

In [13]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

### Step 4: Handle Missing Values

##### Spot strings like "UNKNOWN" and "ERROR" that Pandas doesn't see as nulls yet

converted any "UNKNOWN" and "ERROR" values into np.nan 
by converting df into array and perform boolean mask

done this method in practising file

In [ ]:
# Using boolean mask

mask= df.isin(['UNKNOWN' , 'ERROR'])
print(mask)

      Transaction ID   Item  Quantity  Price Per Unit  Total Spent  \
0              False  False     False           False        False
1              False  False     False           False        False
2              False  False     False           False         True
3              False  False     False           False        False
4              False  False     False           False        False
...              ...    ...       ...             ...          ...
9995           False  False     False           False        False
9996           False  False     False           False        False
9997           False  False     False           False        False
9998           False  False     False           False        False
9999           False  False     False           False        False

      Payment Method  Location  Transaction Date
0              False     False             False
1              False     False             False
2              False     False             False
3               True      True             False
4              False     False             False
...              ...       ...               ...
9995           False      True             False
9996           False     False             False
9997           False     False             False
9998           False     False             False
9999           False     False             False

[10000 rows x 8 columns]

##### Use `.replace()` to convert "UNKNOWN" and "ERROR" to np.nan

In [18]:
df= df.replace( ['UNKNOWN' , 'ERROR'], np.nan)

In [19]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

### Step 5:Text Sanitization

##### remove hidden spaces from all string columns

In [ ]:
# كان ممكن اشيل اي space وقت read_csv

#df=pd.read_csv('\\cafe_sales.csv', skipinitialspace=True)

In [24]:
df['Transaction ID'].str.strip()

0       TXN_1961373
1       TXN_4977031
2       TXN_4271903
3       TXN_7034554
4       TXN_3160411
           ...
9995    TXN_7672686
9996    TXN_9659401
9997    TXN_5255387
9998    TXN_7695629
9999    TXN_6170729
Name: Transaction ID, Length: 10000, dtype: object

In [ ]:
df['Payment Method'].str.strip()

0          Credit Card
1                 Cash
2          Credit Card
3                  NaN
4       Digital Wallet
             ...
9995               NaN
9996    Digital Wallet
9997    Digital Wallet
9998    Digital Wallet
9999              Cash
Name: Payment Method, Length: 10000, dtype: object

In [28]:
df['Location'].str.strip()

0       Takeaway
1       In-store
2       In-store
3            NaN
4       In-store
          ...
9995         NaN
9996         NaN
9997         NaN
9998         NaN
9999    In-store
Name: Location, Length: 10000, dtype: object

In [29]:
df['Item'].str.strip()

0         Coffee
1           Cake
2         Cookie
3          Salad
4         Coffee
          ...
9995      Coffee
9996         NaN
9997      Coffee
9998      Cookie
9999    Sandwich
Name: Item, Length: 10000, dtype: object

##### convert all Item names to lowercase for consistency

In [53]:
df['Item']=df['Item'].str.lower()

##### use a dictionary to fix any typos in item names if they exist

In [54]:
# عشان اعرف في اخطاء املاء هجيب الunique or distenct values
#بعدين هشوف لو في قيم شبه بعضها ب اختلاف الكتابه و اعدلها

if_typo=df['Item'].unique()
print(if_typo)

# No typos

['coffee' 'cake' 'cookie' 'salad' 'smoothie' nan 'sandwich' 'juice' 'tea']

### Step 6: Fix Data Types
##### fix incorrect data types (Quantity, Price Per Unit, Total Spent .....)

In [55]:
print(df.dtypes)

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

In [56]:
df[['Quantity','Price Per Unit','Total Spent']]=df[['Quantity','Price Per Unit','Total Spent']].astype(float)

In [57]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,coffee,2.0,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3.0,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,cookie,3.0,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [58]:
print(df.dtypes)

Transaction ID       object
Item                 object
Quantity            float64
Price Per Unit      float64
Total Spent         float64
Payment Method       object
Location             object
Transaction Date     object
dtype: object

##### identify and fix rows where Quantity might be zero or negative

In [ ]:
less_orequal_0 =(df['Quantity'] <= 0).sum()
print(less_orequal_0)

# all QTYs are higher than 0

0

### Step 7: Handle Missing Values (Part 2: Fill NaNs)

##### fill missing `Price Per Unit`

In [60]:
df['Price Per Unit']=df['Price Per Unit'].fillna(0)

In [62]:
print(df['Price Per Unit'].isnull().sum())

0

##### handle other missing values appropriately (like Payment Method or Location)

In [68]:
mask2 =(df['Total Spent']<=0) & (df['Payment Method'].isna())

df['Payment Method']= np.where(mask2,df['Payment Method'].fillna('not payed'),df['Payment Method'].fillna('other'))

In [73]:
df['Location']=df['Location'].fillna('other')

In [74]:
print(df[['Payment Method','Location']])

      Payment Method  Location
0        Credit Card  Takeaway
1               Cash  In-store
2        Credit Card  In-store
3              other     other
4     Digital Wallet  In-store
...              ...       ...
9995           other     other
9996  Digital Wallet     other
9997  Digital Wallet     other
9998  Digital Wallet     other
9999            Cash  In-store

[10000 rows x 2 columns]

### Step 8: Logical Validation

##### create a new column `Expected_Total` by multiplying `Quantity * Price Per Unit`

In [71]:
df['Expected_Total']=(df['Quantity']*df['Price Per Unit'])

In [75]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Expected_Total
0,TXN_1961373,coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0
1,TXN_4977031,cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,12.0
2,TXN_4271903,cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19,4.0
3,TXN_7034554,salad,2.0,5.0,10.0,other,other,2023-04-27,10.0
4,TXN_3160411,coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0
...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,coffee,2.0,2.0,4.0,other,other,2023-08-30,4.0
9996,TXN_9659401,NaN,3.0,0.0,3.0,Digital Wallet,other,2023-06-02,0.0
9997,TXN_5255387,coffee,4.0,2.0,8.0,Digital Wallet,other,2023-03-02,8.0
9998,TXN_7695629,cookie,3.0,0.0,3.0,Digital Wallet,other,2023-12-02,0.0
9999,TXN_6170729,sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07,12.0

##### filter rows where Total Spent is NOT equal to Expected_Total

In [85]:
df['Total Spent'] = np.where(df['Total Spent'] != df['Expected_Total'], np.nan, df['Total Spent'])

In [86]:
print(df['Total Spent'])

0        4.0
1       12.0
2        NaN
3       10.0
4        4.0
        ...
9995     4.0
9996     NaN
9997     8.0
9998     NaN
9999    12.0
Name: Total Spent, Length: 10000, dtype: float64

##### fill missing or incorrect Total Spent values using the Expected_Total calculation.

In [87]:
df['Total Spent'] = df['Total Spent'].fillna(df['Expected_Total'])

In [88]:
print(df[['Total Spent','Expected_Total']])

      Total Spent  Expected_Total
0             4.0             4.0
1            12.0            12.0
2             4.0             4.0
3            10.0            10.0
4             4.0             4.0
...           ...             ...
9995          4.0             4.0
9996          0.0             0.0
9997          8.0             8.0
9998          0.0             0.0
9999         12.0            12.0

[10000 rows x 2 columns]

### Step 9: Handle Dates

##### convert Transaction Date to datetime

In [89]:
df['Transaction Date']=pd.to_datetime(df['Transaction Date'])

In [91]:
print(df['Transaction Date'].dtype)

datetime64[ns]

In [ ]:
print(df['Transaction Date'].isnull().sum()) # نص قيم التواريخ مفقوده

#there is a data gap since half of dates are missing and no duplicated ids to see if transactions happened on the same day or not
# dropping half of the data will affect other calculations if owner wanted to know revenue or QTY sold or other business KPIs
#:(

460

In [132]:
print(df['Transaction ID'].isnull().sum())
print(df['Transaction ID'].duplicated().sum())

0
0

##### identify transactions with dates in the future (if any) and handle them

In [92]:
import datetime as dt

In [93]:
date_limit= dt.datetime.now()
future_date = df[df['Transaction Date']>date_limit]
print(len(future_date))

0

##### extract "Year" and "Month" into separate columns for analysis

In [102]:
df['Year']=df['Transaction Date'].dt.year

In [134]:
df['Year']=df['Year'].astype('str')

In [115]:
print(df['Year'].dtype)

object

In [111]:
df['Month']=df['Transaction Date'].dt.month_name()

In [119]:
df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Expected_Total,Year,Month
0,TXN_1961373,coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0,2023.0,September
1,TXN_4977031,cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,12.0,2023.0,May
2,TXN_4271903,cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19,4.0,2023.0,July
3,TXN_7034554,salad,2.0,5.0,10.0,other,other,2023-04-27,10.0,2023.0,April
4,TXN_3160411,coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0,2023.0,June
5,TXN_2602893,smoothie,5.0,4.0,20.0,Credit Card,other,2023-03-31,20.0,2023.0,March
6,TXN_4433211,NaN,3.0,3.0,9.0,other,Takeaway,2023-10-06,9.0,2023.0,October
7,TXN_6699534,sandwich,4.0,4.0,16.0,Cash,other,2023-10-28,16.0,2023.0,October
8,TXN_4717867,NaN,5.0,3.0,15.0,other,Takeaway,2023-07-28,15.0,2023.0,July
9,TXN_2064365,sandwich,5.0,4.0,20.0,other,In-store,2023-12-31,20.0,2023.0,December

In [118]:
print(df.dtypes)

Transaction ID              object
Item                        object
Quantity                   float64
Price Per Unit             float64
Total Spent                float64
Payment Method              object
Location                    object
Transaction Date    datetime64[ns]
Expected_Total             float64
Year                        object
Month                       object
dtype: object

### Step 10: Remove Duplicates

##### check for duplicates

In [123]:
df.duplicated().sum()

np.int64(0)

##### drop duplicates if found

In [ ]:
#naaaaaa

### Step 9: Clean Text Data

#####  clean text columns (strip spaces, unify format)

In [135]:
df['Payment Method'] = df['Payment Method'].str.lower()
df['Location'] = df['Location'].str.lower()