importing data

In [2]:
import pandas as pd
"""
ونا بعمل استدعاء للداتا لو هي اونلاين بحط اللينك في متغير 
و المتغير هو اللي اعمله read 

شيلت علامات التنصيص  لان لو حطيتها هيدور ف الجهاز مش علي اللينك
"""

datalink ="https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/09_Time_Series/Apple_Stock/appl_1980_2014.csv"

df = pd.read_csv(datalink)

In [ ]:
""" 
.dtypes to get the data types of all columns as a Series

For mixed-type columns, the type will be object
"""

Handling dates in pandas

In [16]:
# converting a column into date time type
""" 
pd.to_datetime(df['col name'] , format = "write the specetied format in data")

#ممكن مكنش يظبط مع فورماتنج مختلف مثلا لو موجود فيه وقت بالساعات 
# df['Date'] = pd.to_datetime(df['Date'] , format = '%y-%m-%d %i-%p')

"""
df.set_index("Date", inplace=True)

Days

In [6]:
#df.loc[0, 'Date'].day_name()

In [7]:
#df['Date'].dt.day_name()

In [9]:
# to make a column of days of the week
#df['DayofWeek']=df['Date'].dt.day_name()

In [20]:
df.index.max()

'2014-07-08'

In [21]:
df.index.min()

'1980-12-12'

In [ ]:
#Delta date
print(df.index.max()- df.index.min())

TypeError: unsupported operand type(s) for -: 'str' and 'str'

### Resampleing

go to : https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#dateoffset-objects

dealing with dates
بتغيرلي التردد او الفاصل الزمني للداتا

with using Freq

D	تقويم يومي (Calendar day)
W	أسبوعي (Weekly)
M	نهاية الشهر (Month end)
Q	ربع سنوي (Quarter end)
A أو Y	نهاية السنة (Year end)
H	بالساعة (Hourly)


Date must be the index in order for resample to work

In [ ]:
df.resample("M")

### Aggregate

helps in multiple calculations at once
cane be used with resample for weekly ,monthly or even yearly report analysis

In [ ]:
df.resample("W").agg({'Close': "mean",'High':'max'})

### Missing values

In [30]:
df.isnull().head(5)

             Open   High    Low  Close  Volume  Adj Close
Date
2014-07-08  False  False  False  False   False      False
2014-07-07  False  False  False  False   False      False
2014-07-03  False  False  False  False   False      False
2014-07-02  False  False  False  False   False      False
2014-07-01  False  False  False  False   False      False

In [31]:
df.notnull().head(5)

            Open  High   Low  Close  Volume  Adj Close
Date
2014-07-08  True  True  True   True    True       True
2014-07-07  True  True  True   True    True       True
2014-07-03  True  True  True   True    True       True
2014-07-02  True  True  True   True    True       True
2014-07-01  True  True  True   True    True       True

In [ ]:
df.isnull().sum() # sum does the calculations on the axis=0 scale (down columns)

Open         0
High         0
Low          0
Close        0
Volume       0
Adj Close    0
dtype: int64

### What should i do with missing values

In [34]:
# fist droping them
df.dropna(how="any").shape


# dropping any row with NaN value and checking the shape to see how much rows dropped

(8465, 6)

In [ ]:
df.dropna(subset=["Close","Low"],how="any").shape
#if any row in these cols is nan drop it

In [ ]:
df.dropna(subset=["Close","Low"],how="any").shape
#if any row in these cols together is nan drop it

In [ ]:
df.dropna(how="all").shape